name: CI

on:
  push:
    branches:
      - master
      - 'features/**'
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    name: webUi-${{ matrix.browser }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: ["chrome"]

    steps:
      - uses: actions/checkout@v2

      - name: npm-install
        run: npm install

      - name: run chrome tests
        run: |
          mkdir ${{ runner.temp }}/screens
          npx nightwatch tests --env chrome
          echo "Confirming screenshots"
          ls -la screens

      - name: Save Screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: nightwatch-screenshots
          path: ${{ runner.temp }}/screens