name: CI

on:
  push:
    branches:
      - master
      - 'features/**'
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    name: webUi-${{ matrix.browser }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: ["chrome"]

    steps:
      - uses: actions/checkout@v2

      - name: npm-install
        run: npm install

      - name: run chrome tests
        run: |
          # export DISPLAY=:99
          # chromedriver --url-base=/wd/hub &
          # sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & 
          npx nightwatch tests --env chrome