name: CI

on:
  push:
    branches:
      - master
      - 'features/**'
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    name: webUi-${{ matrix.browser }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: ["chrome", "firefox"]

    steps:
      - uses: actions/checkout@v2

      - name: npm-install
        run: npm install

      - name: run browser tests
        run: |
          mkdir screens
          npx nightwatch tests --env ${{ matrix.browser }}

      - name: Save Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: | 
            screens
            tests_output
