name: CI

on:
  push:
    branches:
      - master
      - 'features/**'
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build-linux:
    name: linux-${{ matrix.browser }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: ["chrome", "firefox"]

    steps:
      - uses: actions/checkout@v2

      - name: npm-install
        run: npm install

      - name: run browser tests
        run: |
          mkdir screens
          npx nightwatch tests --env ${{ matrix.browser }}

      - name: Save Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: | 
            screens
            tests_output
            logs

  build-windows:
    name: windows-${{ matrix.browser }}
    runs-on: windows-latest
    env:
      EDGEDRIVER_DOWNLOAD_ON_INSTALL: 1

    strategy:
      matrix:
        browser: ["chrome", "firefox"]

    steps:
      - uses: actions/checkout@v2

      - name: npm-install
        run: npm install

      - name: run browser tests
        run: |
          mkdir screens
          pwd
          echo "Expected gecko driver:"
          dir D:\a\editoria11y\editoria11y\node_modules\geckodriver\bin\
          npx nightwatch tests --env ${{ matrix.browser }} --config tests/nightwatch.windows.conf.js --verbose

      - name: Save Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: | 
            screens
            tests_output
            logs