name: CI

on:
  push:
    branches:
      - master
      - 'features/**'
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build-linux:
    name: linux-${{ matrix.browser }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: ["chrome", "firefox"]

    steps:
      - uses: actions/checkout@v2

      - name: npm-install
        run: npm install

      - name: run browser tests
        run: |
          mkdir screens
          npx nightwatch tests --env ${{ matrix.browser }}

      - name: Save Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: | 
            screens
            tests_output
            logs

  build-windows:
    name: windows-${{ matrix.browser }}
    runs-on: windows-latest
    env:
      EDGEDRIVER_DOWNLOAD_ON_INSTALL: 1

    strategy:
      matrix:
        browser: ["firefox", "edge", "chrome"]

    steps:
      - uses: actions/checkout@v2

      - name: npm-install
        # The "EDGEDRIVER_DOWNLOAD_ON_INSTALL" is nec
        run: |          
          echo "EDGEDRIVER_DOWNLOAD_ON_INSTALL=1" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          npm install

      - name: run browser tests
        run: |
          mkdir screens
          npx nightwatch tests --env ${{ matrix.browser }} --config tests/nightwatch.windows.conf.js --verbose

      - name: Save Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: | 
            screens
            tests_output
            logs

  build-mac:
    name: mac-${{ matrix.browser }}
    runs-on: macos-latest
    env:
      EDGEDRIVER_DOWNLOAD_ON_INSTALL: 1

    strategy:
      matrix:
        browser: ["safari", "chrome"]

    steps:
      - uses: actions/checkout@v2

      - name: npm-install
        run: |          
          npm install

      - name: run browser tests
        run: |
          mkdir screens
          npx nightwatch tests --env ${{ matrix.browser }} --verbose

      - name: Save Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: | 
            screens
            tests_output
            logs